[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
wallex = "DvNur6pprGPLZHobyxoLxAoKvj8E1YjR83m94HperYwz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 ./**/*.ts"

[test]
startup_wait = 100000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"  # USDC
[[test.validator.clone]]
address = "So11111111111111111111111111111111111111112"  # WSOL
[[test.validator.clone]]
address = "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB"  # USDT
[[test.validator.clone]]
address = "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4"  # Jupiter Aggregator
[[test.validator.clone]]
address = "4Ec7ZxZS6Sbdg5UGSLHbAnM7GQHp2eFd4KYWRexAipQT"  # Jupiter Executable Data Account
[[test.validator.clone]]
address = "D8cy77BBepLMngZx6ZukaTff5hCt1HrWyKk3Hnd9oitf"  # Jupiter Aggregator Event Authority
[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
[[test.validator.clone]]
address = "SoLFiHG9TfgtdUXUjWAxi3LtvYuFyDLVhBWxdMZxyCe"
[[test.validator.clone]]
address = "5guD4Uz462GT4Y4gEuqyGsHZ59JGxFN4a3rF6KWguMcJ"
[[test.validator.clone]]
address = "BuAehYMuKCGrdRKQbXutUAtqzdDBKpbvvWwUKrhJPk1H"
[[test.validator.clone]]
address = "48KLHQiGNAUjvsbEk8hFQomg2C7ZZfx69y7LUYGYbBnp"
[[test.validator.clone]]
address = "11111111111111111111111111111111"
[[test.validator.clone]]
address = "56kUfo4V2puE3gL49us9oywGMwjFqzhzE2YktzTCeP7Q"