[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
wallex = "DvNur6pprGPLZHobyxoLxAoKvj8E1YjR83m94HperYwz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

# [[test.validator.account]]
# address = "4Ec7ZxZS6Sbdg5UGSLHbAnM7GQHp2eFd4KYWRexAipQT" # Jupiter Executable Data Account
# filename="/JUP_V6_PROGRAM_DATA_ACCOUNT.json"



[[test.validator.clone]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v" #USDC
[[test.validator.clone]]
address = "So11111111111111111111111111111111111111112" #SOL
[[test.validator.clone]]
address = "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB"  # USDT
[[test.validator.clone]]
address = "4Ec7ZxZS6Sbdg5UGSLHbAnM7GQHp2eFd4KYWRexAipQT"  # Jupiter Executable Data Account
[[test.validator.clone]]
address = "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4"   # Jupiter
[[test.validator.clone]]
address = "D8cy77BBepLMngZx6ZukaTff5hCt1HrWyKk3Hnd9oitf"   # Jupiter Aggregator event athority
[[test.validator.clone]]
address = "4YVLUZGEhsjfsWuxRbo6h18vL297HYRHTrLVE8bwpyCW"  # Meteora DLMM
[[test.validator.clone]]
address = "JDDeNq9GY3E1AVnra9PLoJXyqVaFJPi9L2xrNzMURHXB"  # Meteora DLMM
[[test.validator.clone]]
address = "HRYEjwdo3bZ1TpXKWKcezqiwSV2Ywuh4LxMa2PzoCnG6"  # Meteora DLMM
[[test.validator.clone]]
address = "HTvjzsfX3yU6BUodCjZ5vZkUrAxMDTrBs3CJaq43ashR"  # Meteora DLMM
[[test.validator.clone]]
address = "DJFoQN5yNVtoEhoXiKqmYFXowQcPJSvB3BAavEcdEi7s"  # Meteora DLMM
[[test.validator.clone]]
address = "AvBSC1KmFNceHpD6jyyXBV6gMXFxZ8BJJ3HVUN8kCurJ"  # Orbic V2
[[test.validator.clone]]
address = "Fn68NZzCCgZKtYmnAYbkL6w5NNx3TgjW91dGkLA3hsDK"  # Orbic V2
[[test.validator.clone]]
address = "D94tFiBfJzdZmcH6GtV39iXexWyVpNfwEH3CxEbqvsvr"  # Orbic V2
[[test.validator.clone]]
address = "71GHcjkwmtM7HSWBuqzjEp96prcNNwu1wpUywXiytREU"  # Lifinity V2
[[test.validator.clone]]
address = "HyGVf4UhoQ4ux9ueZgTCf6aJwCcvWqeWf258ZtbeRteV"  # Lifinity V2
[[test.validator.clone]]
address = "BWZHAEz5CPSdiTyUW4Si1Mc4Lr6CLDPwnbFHjaaM7BST"  # OpenBook V2
[[test.validator.clone]]
address = "HPGeZAXNNPzex7QnHP2ZCgyny13BqkNkRg6Lc49PJpdm"  # OpenBook V2
[[test.validator.clone]]
address = "8sLbNZoA1cfnvMJLPfp98ZLAnFSYCFApfJKMbiXNLwxj"  # Raydium CLMM
[[test.validator.clone]]
address = "tqCiSbcbr1QKCv7fNA3gaEgCzTgy8acoghebPhN9XzU"  # Raydium CLMM
[[test.validator.clone]]
address = "6kT4MhDqKrkWikaGpFCvYsk45BUKXEe2gTpNGAR1YcjS"  # Raydium CLMM
[[test.validator.clone]]
address = "CAPhoEse9xEH95XmdnJjYrZdNCA8xfUWdy3aWymHa1Vj"  # SolFi
[[test.validator.clone]]
address = "AHhiY6GAKfBkvseQDQbBC7qp3fTRNpyZccuEdYSdPFEf"  # SolFi
[[test.validator.clone]]
address = "CAPhoEse9xEH95XmdnJjYrZdNCA8xfUWdy3aWymHa1Vj"  # SolFi
[[test.validator.clone]]
address = "FpCMFDFGYotvufJ7HrFHsWEiiQCGbkLCtwHiDnh7o28Q"  # Whirlpool
[[test.validator.clone]]
address = "2SgUGxYDczrB6wUzXHPJH65pNhWkEzNMEx3km4xTYUTC"  # Invariant

[[test.validator.account]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
filename = "./test-account.json"

